apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dug.secrets.name }}
data:
  {{- if .Release.IsInstall }}
  ELASTIC_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  NEO4J_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  REDIS_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  ELASTIC_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.dug.secrets.name )).data "ELASTIC_PASSWORD" }}
  NEO4J_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.dug.secrets.name )).data "NEO4J_PASSWORD" }}
  REDIS_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace ( .Values.dug.secrets.name )).data "REDIS_PASSWORD" }}
  {{ end }}
